### ISSUE TITLE
_prefs has not been initialized

### ISSUE THREAD

**Issue by LongAndHappy** [rlazom/easy_dynamic_theme#5]
I'm receiving the following error after following your example:

```
======== Exception caught by gesture ===============================================================
The following LateError was thrown while handling a gesture:
LateInitializationError: Field '_prefs@682063471' has not been initialized.

When the exception was thrown, this was the stack: 
#0      SharedPreferencesService._prefs (package:easy_dynamic_theme/src/services/shared_preferences_service.dart)
#1      SharedPreferencesService.setIsDark (package:easy_dynamic_theme/src/services/shared_preferences_service.dart:22:7)
#2      _EasyDynamicThemeWidgetState._toggleTheme (package:easy_dynamic_theme/easy_dynamic_theme.dart:136:14)
#3      _EasyDynamicThemeWidgetState.changeTheme (package:easy_dynamic_theme/easy_dynamic_theme.dart:87:7)
#4      _SettingsState.build.<anonymous closure>.<anonymous closure> (package:demo_2_flutter_app/main.dart:414:60)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#2d6eb
  state: ready
  won arena
  finalPosition: Offset(359.7, 261.4)
  finalLocalPosition: Offset(20.6, 24.3)
  button: 1
  sent tap down
====================================================================================================
```

**Comment by rlazom** [comment]
Please @LongAndHappy, could you share the code on your file **main.dart** and your current Flutter version?

**Comment by rlazom** [comment]
This error should be related with "NO INITIALIZATION" in the main.dart file.

So please read more carefully the readme or check the example app provided. ;)

**Comment by AyberkAhmet** [comment]
I am taking kind of same error on windows flutter app. When I start the app, I am taking this error first. Error: "Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)". And I didn't find anything about it in your readme file.

Here my main.dart (imports deleted): 

```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  setup();
  await localNotifier.setup(
    appName: 'HGA CRM',
    // The parameter shortcutPolicy only works on Windows
    shortcutPolicy: ShortcutPolicy.requireCreate,
  );
  runApp(EasyDynamicThemeWidget(
      initialThemeMode: ThemeMode.light, child: const MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider<UserViewModel>(
          create: (_) => UserViewModel(),
        ),
        ChangeNotifierProvider<WorkerViewModel>(
          create: (_) => WorkerViewModel(),
        ),
      ],
      child: MaterialApp(
        localizationsDelegates: const [
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
          SfGlobalLocalizations.delegate
        ],
        supportedLocales: const [
          Locale('de'),
          Locale('tr'),
          Locale('en'),
        ],
        locale: const Locale('de'),
        debugShowCheckedModeBanner: false,
        title: 'Calendar',
        theme: CustomTheme().lightTheme,
        darkTheme: CustomTheme().darkTheme,
        themeMode: EasyDynamicTheme.of(context).themeMode,
        home: const LoginPage(),
      ),
    );
  }
}

```
